#!/bin/bash

set -e

#export PACKER_LOG=1
rm packer_virtualbox-iso_virtualbox.box || true
packer build -only=virtualbox-iso packer.json
vagrant box remove docker_box  || true
vagrant box add docker_box packer_virtualbox-iso_virtualbox.box
